[project]
name = "bench-req"
version = "0.2.0"
description = "HTTP clients benchmarking suite"
readme = "README.md"
authors = [
    { name = "vffuunnyy", email = "vffuunnyy@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "aiohttp>=3.13",
    "httpx[http2]>=0.28",
    "httpcore[http2]>=1.0",
    "niquests>=3.18",
    "impit>=0.12",
    "primp>=1.1",
    "rnet>=3.0.0rc22",
    "requests>=2.32",
    "rich>=14",
    "httpx-aiohttp>=0.1.12",
    "curl-cffi>=0.14.0",
]

[project.scripts]
bench-req = "bench_req.__main__:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
